# Generated by Django 4.1.7 on 2023-03-12 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_before', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото оригінал')),
                ('photo_after', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото колоризоване')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
